# Generated by Django 5.0.7 on 2024-08-01 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, error_messages={'blank': 'Это поле не может быть пустым', 'unique': 'Задача с таким названием уже существует'}, max_length=100, unique=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'blank': 'Это поле не может быть пустым', 'unique': 'Задача с таким названием уже существует'}, help_text='Напишите название задачи', max_length=100, unique=True, unique_for_date='date', verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, help_text='Подробно опишите эту задачу здесь', null=True, verbose_name='Опиcание задачи')),
                ('status', models.CharField(choices=[('New', 'Новая'), ('In Progress', 'В процессе'), ('Pending', 'В ожидании'), ('Blocked', 'Заблокирована'), ('Done', 'Выполнена')], default='New', help_text='Выберите статус задачи', max_length=100, verbose_name='Статус задачи')),
                ('deadline', models.DateTimeField(blank=True, help_text='Укажите здесь дату и время дедлайна, для этой задачи', null=True, verbose_name='Дата и время дедлайна')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Это дата и время, когда задача была создана', verbose_name='Дата и время создания задачи')),
                ('date', models.DateField(auto_now=True, help_text='Дата, к которой относится задача', verbose_name='Дата задачи')),
                ('categories', models.ManyToManyField(help_text='Категории, к которым относится задача', related_name='tasks', to='chudoprilozhenie.category')),
            ],
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'blank': 'Это поле не может быть пустым'}, help_text='Укажите подзадачу для другой задачи', max_length=100, verbose_name='Подзадача для основной задачи')),
                ('description', models.TextField(blank=True, help_text='Опишите подзадачу здесь', null=True, verbose_name='Описание поздадачи')),
                ('status', models.CharField(choices=[('New', 'Новая'), ('In Progress', 'В процессе'), ('Pending', 'В ожидании'), ('Blocked', 'Заблокирована'), ('Done', 'Выполнена')], default='New', help_text='Выберите статус задачи', max_length=100, verbose_name='Статус задачи')),
                ('deadline', models.DateTimeField(blank=True, help_text='Укажите здесь дату и время дедлайна, для этой подзадачи', null=True, verbose_name='Дата и время дедлайна')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Это дата и время, когда подзадача была создана', verbose_name='Дата и время создания подзадачи')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='chudoprilozhenie.task')),
            ],
        ),
    ]
