# Generated by Django 5.0.7 on 2024-08-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chudoprilozhenie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(editable=False, error_messages={'blank': 'Это поле не может быть пустым', 'unique': 'Задача с таким названием уже существует'}, help_text='Напишите здесь название категории', max_length=100, unique=True, verbose_name='Название категории'),
        ),
    ]
