# Generated by Django 5.0.7 on 2024-08-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chudoprilozhenie', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Напишите здесь название категории', max_length=100, unique=True, verbose_name='Название категории'),
        ),
    ]
