# Generated by Django 5.0.7 on 2024-08-08 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chudoprilozhenie', '0004_alter_category_options_alter_subtask_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='chudoprilozhenie.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Категории, к которым относится задача', null=True, related_name='tasks', to='chudoprilozhenie.category'),
        ),
    ]
