# Generated by Django 5.0.7 on 2024-08-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chudoprilozhenie', '0005_alter_subtask_task_alter_task_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='categories',
            field=models.ManyToManyField(help_text='Категории, к которым относится задача', related_name='tasks', to='chudoprilozhenie.category'),
        ),
    ]
